spring.application.name=OrtizSerranoTP3

# Configuración de la Base de Datos H2 (en memoria para desarrollo)
spring.datasource.url=jdbc:h2:mem:decanato_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Deshabilitar scripts SQL automáticos (Hibernate creará las tablas)
spring.sql.init.mode=never

# Habilitar consola H2 para ver la base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Puerto del servidor
server.port=8080

# Configuración JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A
jwt.expiration=86400000
